function(add_files ADD_FILES_OUTPUT ADD_FILES_NAME ADD_FILES_EXTENSION)

  file(GLOB_RECURSE FILES_SOURCE_TMP RELATIVE
    "${CMAKE_CURRENT_SOURCE_DIR}/${ADD_FILES_NAME}"
    "${CMAKE_CURRENT_SOURCE_DIR}/${ADD_FILES_NAME}/*.${ADD_FILES_EXTENSION}")
    
  set(FILES_OUTPUT_TMP "")
  foreach(filename ${FILES_SOURCE_TMP})
    list(APPEND FILES_OUTPUT_TMP ${ADD_FILES_NAME}/${filename})
  endforeach(filename)
  
  source_group("${ADD_FILES_NAME}" FILES ${FILES_OUTPUT_TMP})
 
  set(${ADD_FILES_OUTPUT} ${${ADD_FILES_OUTPUT}} ${FILES_OUTPUT_TMP} PARENT_SCOPE)
  
endfunction()

function(add_source_directory ADD_SOURCE_DIRECTORY_OUTPUT ADD_SOURCE_DIRECTORY_NAME)
  
  add_files(ADD_SOURCE_DIRECTORY_OUTPUT_TMP ${ADD_SOURCE_DIRECTORY_NAME} "cpp")
  add_files(ADD_SOURCE_DIRECTORY_OUTPUT_TMP ${ADD_SOURCE_DIRECTORY_NAME} "h")
  
  set(${ADD_SOURCE_DIRECTORY_OUTPUT} ${${ADD_SOURCE_DIRECTORY_OUTPUT}} ${ADD_SOURCE_DIRECTORY_OUTPUT_TMP} PARENT_SCOPE)
 
endfunction()

function(add_ui_directory ADD_UI_DIRECTORY_OUTPUT ADD_UI_DIRECTORY_NAME)
  
  add_files(ADD_UI_DIRECTORY_OUTPUT_TMP ${ADD_UI_DIRECTORY_NAME} "ui")
  
  set(${ADD_UI_DIRECTORY_OUTPUT} ${${ADD_UI_DIRECTORY_OUTPUT}} ${ADD_UI_DIRECTORY_OUTPUT_TMP} PARENT_SCOPE)
 
endfunction()

function(add_other_directory ADD_OTHER_DIRECTORY_OUTPUT ADD_OTHER_DIRECTORY_NAME)
  
  add_files(ADD_OTHER_DIRECTORY_OUTPUT_TMP ${ADD_OTHER_DIRECTORY_NAME} "*")
  
  set(${ADD_OTHER_DIRECTORY_OUTPUT} ${${ADD_OTHER_DIRECTORY_OUTPUT}} ${ADD_OTHER_DIRECTORY_OUTPUT_TMP} PARENT_SCOPE)
 
endfunction()
